### ISSUE TITLE
不知是不是BUG

### ISSUE THREAD

**Issue by jetlwx** [withlin/canal-go#33]
场景：
1）所有组件均正常运行中。。
2）canal-go开始读取数据，读了一会，提示没有数据，然后很长一段时间，比如1分钟，仍然提示没有数据，但是当使用CTRL＋C终止客户端后，再重运行，突然会有一堆数据出来。

3）此情况，应该可以重现，不知是否BUG？

**Comment by withlin** [comment]
我刚才测试了下，本地没有问题呢。应该是你的控制台阻塞了把，按一下多按几下Enter试试把。

**Comment by jetlwx** [comment]
感觉不是阻塞了，因为屏幕一直在输出 ＝＝没有数据了＝＝，我怀疑，按CTRL＋C后，客户端好像双从上次读取的开始点，又重新读一次。

**Comment by jetlwx** [comment]
哦，对了，少量数据是没有问题，你可以接一下某个测试系统，也就是比较忙的binlog，应该可以重现

**Comment by withlin** [comment]
@jetlwx 你没有ack，就会重读。


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
