### ISSUE TITLE
处理ack数据时为什么需要panic？

### ISSUE THREAD

**Issue by jingyugao** [withlin/canal-go#39]
https://github.com/withlin/canal-go/pull/38/commits/3a7ee2395d3ac92e24e59f633e3d57bcb92ad583#diff-c4b62398375776a7a64942ec90c82994L347
```
	case PacketType_ACK:
		err := proto.Unmarshal(p.Body, ack)
		if err != nil {
			return nil, err
		}
		panic(errors.New(fmt.Sprintf("something goes wrong with reason:%s", ack.GetErrorMessage())))
```
代码如上，解析后如果err为空为什么需要panic呢？

**Comment by withlin** [comment]
你可以看一下[SimpleCanalConnector.java](https://sourcegraph.com/github.com/alibaba/canal/-/blob/client/src/main/java/com/alibaba/otter/canal/client/impl/SimpleCanalConnector.java#L186)
我只是按照java的来实现的，有啥问题，您可以给官方提issue。

**Comment by laughcat** [comment]
> [3a7ee23#diff-c4b62398375776a7a64942ec90c82994L347](https://github.com/withlin/canal-go/commit/3a7ee2395d3ac92e24e59f633e3d57bcb92ad583#diff-c4b62398375776a7a64942ec90c82994L347)
> 
> ```
> 	case PacketType_ACK:
> 		err := proto.Unmarshal(p.Body, ack)
> 		if err != nil {
> 			return nil, err
> 		}
> 		panic(errors.New(fmt.Sprintf("something goes wrong with reason:%s", ack.GetErrorMessage())))
> ```
> 
> 代码如上，解析后如果err为空为什么需要panic呢？

请问这里有解决吗？我也碰到这个panic问题了
