### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by jackerzz** [withlin/canal-go#43]
![5dac6daaf23fd64fbe53f5dbaa7a8ac](https://user-images.githubusercontent.com/35586448/69510206-e160da80-0f76-11ea-88ab-64f8913a56f2.png)

**Comment by withlin** [comment]
数据库的编码是什么?

**Comment by jackerzz** [comment]
![image](https://user-images.githubusercontent.com/35586448/69516357-60144280-0f8c-11ea-8dc3-6109e2af8fd5.png)

**Comment by jackerzz** [comment]
感谢你一语惊醒梦中人，我修改啦字符集为utf-8后就可以啦
