### ISSUE TITLE
canal-go 不支持1.1.4版本的Canal server！！！

### ISSUE THREAD

**Issue by dd01xiejunsheng** [withlin/canal-go#44]
我下載了最新版的Canal server， 版本号是1.1.4， 然后用php版的canal client连接做测试， 都能正常使用， 后来准备用Go版本的canal client， 一连接， 发现怎么改数据库， 都是提示:===没有数据了===,  这我就郁闷了， 再详细看你们的文档， 是用docker环境来run mysql和canal server. 我就尝试下， 发现docker环境用的canal server居然是1.1.0版本的， 然后发现居然能用了。。。go版本的client什么时候能支持 1.1.4 版本的 canal server???

**Comment by withlin** [comment]
您好，最近有点忙，有空的时候看一下。

**Comment by brz233** [comment]
样例中修改过滤器参数，`err = connector.Subscribe(".*\\..*")`，[https://github.com/alibaba/canal/wiki/AdminGuide](https://github.com/alibaba/canal/wiki/AdminGuide)
