### ISSUE TITLE
配置访问账号和密码后，总是返回EOF错误

### ISSUE THREAD

**Issue by WangRest** [withlin/canal-go#46]
在canal-server中配置了如下的访问控制方式
```ini
# canal instance user/passwd
canal.user = canal
canal.passwd = E3619321C1A937C46A0D8BD1DAC39F93B27D4458
```

使用`canal-go`的代码
```go
connector := client.NewSimpleCanalConnector("192.168.199.17", 11111, "canal", "canal", "example", 60000, 60*60*1000)
err:=connector.Connect()
```
`err`总是为`EOF`错误

但在使用`Java`客户端时，能正常连接 https://github.com/alibaba/canal/tree/master/example

**Comment by withlin** [comment]
你好最近有点忙 放假的时候我看一下吧。

**Comment by Torival** [comment]
今天升级canal到1.4也发现了这个问题。对比了下go client和java client，go版本的没有对passwd进行加密。可以先临时修改server里canal.passwd为空，然后go client也传空。

**Comment by Darrenzzy** [comment]
你好，麻烦问下这个密码加密问题什么时候可以修复？

**Comment by withlin** [comment]
已经修复
