### ISSUE TITLE
进程内不支持创建多个客户端

### ISSUE THREAD

**Issue by pescaria** [withlin/canal-go#47]
客户端操作的连接用全局变量，当需要在一个进程内创建多个实例连接时，会导致交互错乱

**Comment by withlin** [comment]
肯定是不支持的。 java的也不支持

**Comment by pescaria** [comment]
把 conn 绑定到 Connector，这样是不是好点，我们这边场景是需要同一个进程器读取多个实例，然后每个实例新建一个Connector 就可以了。
