### ISSUE TITLE
没法获取到变更的数据信息，只能获取到EntryType_TRANSACTIONBEGIN和EntryType_TRANSACTIONEND

### ISSUE THREAD

**Issue by Xsxdot** [withlin/canal-go#49]
1. go的结果
![截屏2020-03-11下午3 34 56](https://user-images.githubusercontent.com/24730668/76393204-09e9d480-63ae-11ea-9aee-4d3e5f2bc33f.png)
2. java的结果
![截屏2020-03-11下午3 35 05](https://user-images.githubusercontent.com/24730668/76393218-11a97900-63ae-11ea-848b-1570cd905612.png)

 debug后发现只能获取到事务开始和事务结束的entry

canal-server只改过ip之类的信息，使用的集群模式

**Comment by Xsxdot** [comment]
经过验证，在单机模式下是好的，能正常收到数据，但是将canal转为集群模式就不可以了

**Comment by Xsxdot** [comment]
非常神奇的事情,通过NewClusterCanalConnector连接到canal是获取不到详细数据的，但是通过GetNode获取到节点地址和IP之后，再使用NewSimpleCanalConnector连接，是可以正常获取到数据的，可能跟canal没有太大关系，而是跟NewClusterCanalConnector进行Connect后的一些操作有关系
![截屏2020-03-12上午10 24 03](https://user-images.githubusercontent.com/24730668/76481119-a1e9cb80-644b-11ea-8b49-5fc7c17a25be.png)

**Comment by withlin** [comment]
这个  NewClusterCanalConnector 是别人贡献的，如果你觉得哪里不好使的，可以给我提个pr，我有空看看。最近有点忙。 tks.

**Comment by Xsxdot** [comment]
已提，并加了点东西
