### ISSUE TITLE
消费数据中断

### ISSUE THREAD

**Issue by nothing-do** [withlin/canal-go#53]
我按照Demo连接了测试的canal ，但发现数据成功消费了一部分后，就不再消费这是怎么回事（实际是有数据更新的）
![image](https://user-images.githubusercontent.com/34049150/78571493-d426f700-7858-11ea-8c8b-75d4e3d82d4c.png)

**Comment by withlin** [comment]
你可以看一下 服务端是否有报错。

**Comment by nothing-do** [comment]
> 你可以看一下 服务端是否有报错。

嗯  服务端报错了  已经修复  感谢
