### ISSUE TITLE
canal 1.1.5 连接启动失败

### ISSUE THREAD

**Issue by comin2013** [withlin/canal-go#71]
panic: runtime error: slice bounds out of range [:10004] with capacity 240 [recovered]
        panic: runtime error: slice bounds out of range [:10004] with capacity 240

goroutine 19 [running]:
github.com/samuel/go-zookeeper/zk.decodePacket.func1(0xc00022de68)
        D:/GoPath/pkg/mod/github.com/samuel/go-zookeeper@v0.0.0-20180130194729-c4fab1ac1bec/zk/structs.go:398 +0xfe
panic(0xc65aa0, 0xc000416000)
        C:/Program Files/Go/src/runtime/panic.go:969 +0x1c7
github.com/samuel/go-zookeeper/zk.decodePacketValue(0xc000400010, 0x0, 0xf0, 0xc13760, 0xc00040a010, 0x197, 0x197, 0x0, 0x0)
        D:/GoPath/pkg/mod/github.com/samuel/go-zookeeper@v0.0.0-20180130194729-c4fab1ac1bec/zk/structs.go:474 +0xa4a
github.com/samuel/go-zookeeper/zk.decodePacketValue(0xc000400000, 0x10, 0x100, 0xc08e60, 0xc00040a000, 0x16, 0x10, 0x100, 0xc00022de28)
        D:/GoPath/pkg/mod/github.com/samuel/go-zookeeper@v0.0.0-20180130194729-c4fab1ac1bec/zk/structs.go:433 +0x471
github.com/samuel/go-zookeeper/zk.decodePacket(0xc000400000, 0x10, 0x100, 0xc08e60, 0xc00040a000, 0x0, 0x0, 0x0)
        D:/GoPath/pkg/mod/github.com/samuel/go-zookeeper@v0.0.0-20180130194729-c4fab1ac1bec/zk/structs.go:407 +0x178
github.com/samuel/go-zookeeper/zk.(*Conn).authenticate(0xc000224420, 0x0, 0x0)
        D:/GoPath/pkg/mod/github.com/samuel/go-zookeeper@v0.0.0-20180130194729-c4fab1ac1bec/zk/conn.go:726 +0x45b
github.com/samuel/go-zookeeper/zk.(*Conn).loop(0xc000224420)
        D:/GoPath/pkg/mod/github.com/samuel/go-zookeeper@v0.0.0-20180130194729-c4fab1ac1bec/zk/conn.go:486 +0x65
github.com/samuel/go-zookeeper/zk.Connect.func1(0xc000224420)
        D:/GoPath/pkg/mod/github.com/samuel/go-zookeeper@v0.0.0-20180130194729-c4fab1ac1bec/zk/conn.go:223 +0x36
created by github.com/samuel/go-zookeeper/zk.Connect
        D:/GoPath/pkg/mod/github.com/samuel/go-zookeeper@v0.0.0-20180130194729-c4fab1ac1bec/zk/conn.go:222 +0x4b8

**Comment by comin2013** [comment]
顺带说 一下, 我用simpleclient建立多个连接的时候, 也有订阅混乱的问题...

**Comment by withlin** [comment]
订阅问题参考 [issue-canal-1744](https://github.com/alibaba/canal/issues/1744)

**Comment by zzxn** [comment]
请问现在canal适配到什么版本？

**Comment by withlin** [comment]
@zzxn 没记错的话是 1.14
