### ISSUE TITLE
canal-go如何进行数据库全量同步，adapter可以通过curl，这种client通过什么全量同步？

### ISSUE THREAD

**Issue by wardseptember** [withlin/canal-go#73]
canal-go如何进行数据库全量同步，adapter可以通过curl，这种client通过什么全量同步？

**Comment by withlin** [comment]
你可以用mysql-dump做全量导出。用golang包装一层。读取mysql的-dump的std.out。输出后解析-处理-存储

**Comment by wardseptember** [comment]
大数据量也这样办吗，6亿多条。我直接where id >= ? and id <= ?，这种查询出来再写入可靠吗？

**Comment by withlin** [comment]
当然不可靠啊，百度 `mysql-dump`

**Comment by withlin** [comment]
参考 [go-mysql-elasticsearch](https://github.com/go-mysql-org/go-mysql-elasticsearch)
