### ISSUE TITLE
UnSubscribe方法根本就会真正取消订阅  

### ISSUE THREAD

**Issue by wowo666** [withlin/canal-go#77]
好多地方的c.Running的判断完全无意义， 且真正需要运行的逻辑根本没执行到

![image](https://user-images.githubusercontent.com/33107589/159726044-7a1ec9bf-2550-42f5-aaa5-12c3c513f6ea.png)
![image](https://user-images.githubusercontent.com/33107589/159726407-e1117e64-4501-4a55-81b7-e0fb2f458ab6.png)
![image](https://user-images.githubusercontent.com/33107589/159726533-276cc5a0-c7c8-4523-87cd-0d3355939d3c.png)
![image](https://user-images.githubusercontent.com/33107589/159726611-74ea8206-8b75-44f9-9641-ac62aed67fa4.png)

**Comment by withlin** [comment]
这只是参照 java写的而已，其实也是可以去掉的
