### ISSUE TITLE
使用nohup go run xx.go 2&>1 /dev/null 时，运行一段时间CPU飙升100% 返回的都是EOF

### ISSUE THREAD

**Issue by yhuaminghui** [withlin/canal-go#79]
获取ps进程ID后kill掉，发现没用，后台使用top命令发现CPU占用100%的main函数，kill掉后才算是结束掉
测试过程中不使用nohup 没发现什么问题
求教

**Comment by withlin** [comment]
应该是服务端没有数据吧？ 看下是不是canal-server 有问题？
