### ISSUE TITLE
mysql5.7.38配置文件需要调整一下才能抓取到变更

### ISSUE THREAD

**Issue by flybeta1988** [withlin/canal-go#81]
![docker/mysql/mysqld.cnf调整](https://cdn.xnwimg.com/down/f:%7BF5E8D1A2-A82E-4E6F-29A8-D13161A52908%7D/mysql5.7-mysqld.cnf.png)
![docker/docker-compose.yml调整](https://cdn.xnwimg.com/down/f:%7B8CEFAA10-3CE1-7D49-04D9-21973BFDBE72%7D/canal-docker-composer.png)

**Comment by withlin** [comment]
done
