### ISSUE TITLE
[连接泄露]执行Get方法时会导致连接泄露

### ISSUE THREAD

**Issue by RussGan** [withlin/canal-go#85]
canal-go版本：v1.1.1
问题描述：
![suOd8Kqkws](https://user-images.githubusercontent.com/46184874/236148681-878d144b-c307-4ed3-8a72-e156f06f97ff.jpg)
在执行上述逻辑时，首先会有莫名的err导致执行reconnect操作。在执行reconnect逻辑时应该先将之前的连接断连，再建立新的连接。

**Comment by RussGan** [comment]
现在的实现会导致连接泄露

**Comment by withlin** [comment]
@RussGan  哪里导致泄露？通过什么办法判定？
