### ISSUE TITLE
例子的proto.Unmarshal(entry.GetStoreValue(), rowChange) 出现错误

### ISSUE THREAD

**Issue by hjw33210** [withlin/canal-go#91]
无法将 'rowChange' (类型 *pbe.RowChange) 用作类型 Message 类型未实现 'Message'，因为缺少某些方法: ProtoReflect() Message

**Comment by code-innovator-zyx** [comment]
修改proto包 ，将 "google.golang.org/protobuf/proto" 修改为 "github.com/golang/protobuf/proto" 包

**Comment by zzx000** [comment]
master 版本1.33.0 了，最新的tags 还在1.1.1 , 引用的包太老了，和例子的方法对不上。即使把这个异常解决了，用的也不是最新版本。可以把代码import 到自己仓库， git tag  自己的版本，引用自己的包。最好的方法是，官方自己更新一下。
